services:
    resticprofile:
        image: creativeprojects/resticprofile:latest
        container_name: resticprofile
        volumes:
            # Required
            - ./cfg:/cfg
            - ${APP_DATA_FOLDER}/cache:/cache
            - ${SECRETS_ENV_FILE}:/cfg/password.txt:ro
            # Optional
            - ${LOCAL_BACKUP_FOLDER}:/backup_repo
            - ${RESTORE_FOLDER}:/restore
            # Folders (add :ro at end)
            - ${PHOTOS_FOLDER}:/Photos:ro
            # Apps (add :ro at end)
            - ${IMMICH_DB_DUMPS_FOLDER}:/immich:ro
            - ${NPM_APP_DATA_FOLDER}:/npm:ro
            - ${FILE_UPLOAD_APP_DATA_FOLDER}:/file-upload:ro
        working_dir: /cfg
        environment:
            RESTIC_CACHE_DIR: /cache
        restart: "no"